project:
  type: website

website:
  title: "Stefan Vermeent"
  navbar:
    background: primary
    search: true
    left:
      - cv.qmd
      - publications.qmd
      - talks.qmd
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

