project:
  type: website

website:
  title: "Stefan Vermeent"
  navbar:
    background: primary
    search: true
    left:
      - cv.qmd
      - publications.qmd
      - talks.qmd
    right:
      - icon: github
        href: https://github.com/stefanvermeent
        aria-label: GitHub
  favicon: images/stefan.jpg
  twitter-card: true
  google-analytics: 
    tracking-id: "G-00WCWLW0KH"
    storage: none
    anonymize-ip: true
  

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

